Composition *--
Aggregation o--
Extension <|--
Instantiates -.>
@startuml
' ---Car related classes---
class Car{}
    class Engine{}
        class LiquidEngine{}
        class ElectricEngine{}
        class GaseousEngine{}
    class Fuel{}
        class LiquidFuel{}
            class BenzineLiquidFuel{}
            class DieselLiquidFuel{}
        class ElectricFuel{}
            class FastElectricFuel{}
            class SlowElectricFuel{}
        class GaseousFuel{}
            class LNGGaseousFuel{}
            class HydrogenGaseousFuel
    class Model{}
        class Cabrio{}
        class Tank{}
        class Crossover{}
        class Sedan{}
        class SUV{}
    class Type{}
        class RaceAuto{}
        class LegerAuto{}
        class GewoneAuto{}




' ---Factory classes

class Factory{}
class Dealer{
    Car[] cars
}
class Customer{
    Car[] cars
}


Car "0..inf"--o "1" Customer
Car "0..inf"--o "1" Dealer
Car <.- Factory : "Produces"
Dealer <.-  Customer : "Buys"
Dealer -.> Factory : "Buys"



@enduml